### ISSUE TITLE
Using BroadcastChannel over localStorage

### ISSUE THREAD

**Issue by NadavKolodner** [storeon/crosstab#10]
Hello!
Is there any reason you chose to use LocalStorage for your crosstab implementation over the newer, faster, [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API)? ([or a usage of BroadcastChannel with polyfills?](https://github.com/pubkey/broadcast-channel))

**Comment by ivan-solovev** [comment]
Hi! I know about this API. It has very little browser support. And you will always need to connect polyfill for it to work. Switching to the BroadcastChannel is not a plus for this package.
I don't think that's a good idea.

**Comment by NadavKolodner** [comment]
It seems like [IE, Opera, and Safari](https://caniuse.com/#feat=broadcastchannel) are the only unsupported browsers anymore... But yeah, good point, without good polyfills (which would add bulk to the package) it would not be backwards compatible
Thanks!
