### ISSUE TITLE
Allow to sync only specific part of the state

### ISSUE THREAD

**Issue by ai** [storeon/crosstab#4]
Right now you synchronize the whole state. Most users will need to synchronize only part of the state.

The second question, do we need to sync state or it will be better to sync `dispatch` calls and initial state will be synced by `@storeon/localstorage` (in this case we still need some callback filter for actions)?

**Comment by ivan-solovev** [comment]
I fixed the module. Now only events are synchronized.

**Comment by ai** [comment]
Great. Much better.

Can you replace `@sync` event with global variable? It could reduce size.

**Comment by ivan-solovev** [comment]
I added the global variable for the event of sync. And reduced the module size from 222 to 189 bytes.

**Comment by ai** [comment]
1. I mean do not dispatch any event at all. If you need to block your event listeners you can do `ignoreNext = true`
2. You need to add option to pass callback to filter events. Not every event should be synchronized.

**Comment by ivan-solovev** [comment]
I resolved.
