### ISSUE TITLE
Crossworker and crosssocket 🙃

### ISSUE THREAD

**Issue by jeetiss** [storeon/crosstab#7]
Hello, thanks for great libs

I made plugin for figma and use copy paste of this module for synchronize states between ui and plugin workers. Maybe create some abstraction for synchronization states, and use it here and in other cases (sync state through websockets, figma plugins, workers and so)

It can be like 

```js
function syncState (config) {
  var send = config.send
  var subscribe = config.subscribe
  var filter = config.filter
  
  var ignoreNext = false;

  return function (store) {
    store.on('@dispatch', function(_, event) {
      if (event[0][0] === '@') return;

      if (ignoreNext) {
        ignoreNext = false;
        return;
      }

      if (filter && !filter(event[0], event[1])) return;

      send([event[0], event[1]]);
    });

    subscribe((tip) => {
      ignoreNext = true;
      store.dispatch(tip[0], tip[1]);
    });
  };
};
```

Usage: https://github.com/jeetiss/secret-figma-plugin/blob/master/src/plugin/index.ts#L19-L24

What do you think about it?)

**Comment by jeetiss** [comment]
viva [crossstore](https://github.com/jeetiss/storeon-crossstore) 🙌🏻

**Comment by ivan-solovev** [comment]
Hey. I think this is excessive functionality for this plugin.

**Comment by ivan-solovev** [comment]
This can be done through Storeon.
